<?xml version="1.0"?>
<!-- This is a simple model of an inverted pendulum on a cart. The cart is
     constrained to move along a rail, and the pendulum is attached to the
     cart. The pendulum is free to rotate about the cart, and the cart is
     free to move along the rail. -->



<!-- Main URDF file -->
<!-- URDF generally uses meters, kilograms, and radians for lengths, masses, and angles, respectively -->


<robot name="inverted_pendulum" xmlns:xacro="http://www.ros.org/wiki/xacro">    

  
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="length_slider" value="0.5" /> <!-- pole length -->
    <xacro:property name="mass_slider" value="100" />
    <xacro:property name="mass_cart" value="20.0" />
    <xacro:property name="m_rod" value="2.0" />
    <xacro:property name="m_mass" value="0.05" />
    <xacro:property name="length_rod" value="0.4" />
    <xacro:property name="radius_rod" value="0.005" />
    <xacro:property name="radius" value="0.05" /> 

    <xacro:property name="rail_height" value="0.02" />
  
    <xacro:property name="friction_cart" value="0.5" />
    <xacro:property name="friction_rod" value="0.1" />
 
    <xacro:property name="inertia_rod" value="0.006" />
    <xacro:property name="inertia_cart" value="0.05" />
    <xacro:property name="inertia_slider" value="0.05" />

    <xacro:property name="cart_width" value="0.05" /> 
    <xacro:property name="cart_height" value="0.025" /> 
    <xacro:property name="cart_depth" value="0.1" /> 

    <xacro:property name="gravity" value="9.81" />

    <xacro:include filename="material_calculations.xacro" />



  <!-- Declare variables -->
  <link name="world"/>

  <joint name="base_joint" type="fixed">
      <origin xyz="1.5 1.0 0" rpy="0 0 0"/>
      <parent link="world"/>
      <child link="base_link"/>        
  </joint>

  <link name="base_link">
    <visual>
        <origin xyz="0 0 0.05" rpy="0 0 0"/>
        <geometry>
            <box size="2.5 1.5 0.1" />
        </geometry>
        <material name="green">
            <color rgba="0.2 1 0.2 1"/>
        </material>
    </visual>
    <collision>
        <origin xyz="0 0 0.05" rpy="0 0 0"/>
        <geometry>
            <box size="2.5 1.5 0.1" />
        </geometry>
    </collision>
    <inertial>
        <origin xyz="0 0 0.05" rpy="0 0 0"/>
        <mass value="12" />
        <inertia ixx="2.26" ixy="0.0" ixz="0.0" iyy="6.26" iyz="0.0" izz="8.5" />
    </inertial>
</link>
  
<!-- Rail Link -->
  <link name="rail">
    <static>true</static>
    <inertial> 
      <mass value="${mass_slider}" /> <!-- No inertia as it is a static link -->
      <inertia
        ixx="${mass_slider*length_slider*length_slider/12}" ixy="0.0" ixz="0.0"
        iyy="0.0" iyz="0.0"
        izz="${mass_slider*length_slider*length_slider/12}"/>
     </inertial>
    <visual>
      <material name="black"/>
      <geometry>
        <box size="0.5 0.02 0.02" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="0.5 0.02 0.02" />
      </geometry>
    </collision>
  </link>

    <!-- Fixed joint to fix robot to Gazebo 'base_link' -->
  <joint name="rail_fixed" type="fixed">
    <parent link="base_link"/>
    <child link="rail"/>
    <origin xyz="0 0 0.11" rpy="0 0 0" />
  </joint>
  
  <!-- Cart Link -->
  <link name="cart">
    <inertial>
      <mass value="${mass_cart}" /> <!-- Design parameter, adjust as needed -->
      <inertia 
        ixx="${mass_cart*(cart_depth*cart_depth+cart_height*cart_height)/12}" ixy="0.0" ixz="0.0"
        iyy="${mass_cart*(cart_depth*cart_depth+cart_width*cart_width)/12}" iyz="0.0"
        izz="${mass_cart*(cart_width*cart_width+cart_height*cart_height)/12}"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${cart_width} ${cart_depth} ${cart_height}" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${cart_width} ${cart_depth} ${cart_height}" />
      </geometry>
    </collision>
  </link>

    <!-- Joint connecting rail and cart -->
  <joint name="rail_cart_joint" type="prismatic">
    <parent link="rail" />
    <child link="cart" />
    <origin xyz="0 0 0.01" rpy="0 0 0" />
    <axis xyz="1 0 0" />
    <limit lower="-0.25" upper="0.25" effort="100" velocity="2"/>
    <dynamics damping="${friction_cart}" />  <!-- Estimated damping coefficient -->
  </joint>
  

 <!-- Pendulum Rod Link -->
  <link name="pendulum_rod">
    <inertial>
      <origin xyz="0 0 ${length_rod/2}" rpy="0 0 0" />
      <mass value="${m_rod}" /> <!-- Design Var -->
      <inertia 	  
        ixx="${m_rod*length_rod*length_rod/3}" ixy="0.0" ixz="0.0"
        iyy="0.0" iyz="0.0"
        izz="${m_rod*length_rod*length_rod/3}"/> 
    </inertial>
    <visual>
      <geometry>
        <cylinder length="${length_rod}" radius="0.005"/>
      </geometry>
      <material name="purple"/>  
       <origin xyz="0 0 -${length_rod/2}" rpy="0 0 0" />
    </visual>
    <collision>
        <geometry>
          <cylinder length="${length_rod}" radius="0.005"/>
        </geometry>
        <origin xyz="0 0 -${length_rod/2}" rpy="0 0 0" />
    </collision>
  </link>

    <!-- Joint connecting cart and pendulum rod -->
  <joint name="cart_pendulum_rod_joint" type="revolute">
    <parent link="cart" />
    <child link="pendulum_rod" />
    <origin  xyz="0 ${-cart_depth/2-radius_rod}  0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <dynamics damping="${friction_rod}" />  <!-- Estimated damping coefficient -->
    <limit effort="1000.0" lower="${PI/2}" upper = "${PI +(PI/2)}" velocity="1000.0"/>
    <gazebo>
    <provideFeedback>true</provideFeedback>
  </gazebo>
  </joint>

<!-- Pendulum Mass Link  at the top of the pendulum -->
  <link name="pendulum_mass">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="${m_mass}" />  <!-- 50-100g -->
      <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
    <visual>
      <geometry>
        <sphere radius="0.01"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="0.01"/>
        </geometry>
    </collision>
  </link>

  <!-- Joint connecting pendulum rod and pendulum mass -->
  <joint name="pendulum_rod_mass_joint" type="fixed">
    <parent link="pendulum_rod" />
    <child link="pendulum_mass" />
    <origin xyz="0 0 -${length_rod}" rpy="0 0 0" />
  </joint>

  <xacro:include filename="sensors.xacro" />

</robot>


